server:
  # 端口
  port: 7012
# spring相关的配置
spring:
  application:
    # 应用名称
    name: ytrue-admin
  profiles:
    active:
      #      - @profileActive@
      - dev
  main:
    #允许Bean重复注入，后者覆盖前者
    allow-bean-definition-overriding: true

