server:
  # 端口
  port: 7000

# spring相关的配置
spring:
  application:
    # 应用名称
    name: ytrue-admin
  main:
    # 允许Bean重复注入，后者覆盖前者
    allow-bean-definition-overriding: true
  # mysql 配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/ytrue-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    # 账号
    username: root
    # 密码
    password: root
    # Hikari 连接池配置
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 判断连接是否有效
      connection-test-query: select 1
  # 定时任务
  quartz:
    # 数据库
    job-store-type: jdbc
    jdbc:
      # always配置的意思是，每次初始化都会重新生成表(执行一次删除，执行一次创建)，生成后，可以修改为 never
      initialize-schema: never
  # redis配置
  redis:
    # 地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # 指定数据库，默认为0
    database: 0
    # 连接超时时间，单位毫秒，默认为0
    timeout: 30000
    # 是否启用SSL连接，默认false
    ssl: false
    # jedis客户端连接方式是基于tcp的阻塞式连接方式,
    # lettuce客户端连接方式是基于netty的多路复用异步非阻塞的连接方案
    # 这里选择 lettuce
    lettuce:
      pool:
        # 最大活跃连接数，默认8个
        max-active: 8
        # 最大空闲连接数，默认8个。
        max-idle: 8
        # 获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
        max-wait: -1
        # 最小空闲连接数，默认0
        min-idle: 0
  # freemarker配置
  freemarker:
    check-template-location: false

  # springboot admin 配置
  boot:
    admin:
      client:
        url: http://127.0.0.1:7001

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        #暴露部分端点
        include: '*'
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always

# mybatis plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  configuration:
    # 使用Mybatis时，如果查询语句中某些字段值是null的，则这个字段就无法返回，这里可以设置为true
    call-setters-on-nulls: true
    # 打印sql语句
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

# 设置日志级别
logging:
  level:
    com.ytrue: debug

