server:
  # 端口
  port: 7000
# spring相关的配置
spring:
  application:
    # 应用名称
    name: ytrue-admin
  # freemarker配置
  freemarker:
    check-template-location: false
  # 在家外部的配置文件
  config:
    import:
      - classpath:/config/dev/db.yml
      - classpath:/config/dev/doc.yml
      - classpath:/config/dev/monitor.yml
      - classpath:/config/dev/mybatis.yml
      - classpath:/config/dev/quartz.yml
      - classpath:/config/dev/redis.yml
      - classpath:/config/dev/ytrue.yml

# 设置日志级别
logging:
  level:
    com.ytrue: info

