spring:
  # redis配置
  redis:
    # 地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # 指定数据库，默认为0
    database: 0
    # 连接超时时间，单位毫秒，默认为0
    timeout: 30000
    # 是否启用SSL连接，默认false
    ssl: false
    # jedis客户端连接方式是基于tcp的阻塞式连接方式,
    # lettuce客户端连接方式是基于netty的多路复用异步非阻塞的连接方案
    # 这里选择 lettuce
    lettuce:
      pool:
        # 最大活跃连接数，默认8个
        max-active: 8
        # 最大空闲连接数，默认8个。
        max-idle: 8
        # 获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
        max-wait: -1
        # 最小空闲连接数，默认0
        min-idle: 0
