# 针对ytrue配置
ytrue:
  # 安全配置
  security:
    auth-type-parameter-name: auth_type
    authorization-header-parameter-name: BearerAuth
    token-cache-prefix: 'login_auth_tokens:'
    # 这个必须要与你认证的接口保存一致
    auth-url: /login
    jwt:
      token-expire-time: 360000000
    ignoring:
      pattern:
        - /favicon.ico
        - /error
        - /actuator
        - /actuator/**
        - /webjars/**
        - /v3/api-docs/**
        - /swagger**
        - /swagger-ui/**
        - /doc.html
        - /storage/**
        - /static/storage/**
  # 开启操作日志监听
  log:
    enabled: true
  storage:
    local:
      domain: http://192.168.110.139:7000
      file-host: storage
